from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_SumaVectores(object):
    def setupUi(self, SumaVectores):
        SumaVectores.setObjectName("SumaVectores")
        SumaVectores.resize(551, 424)
        SumaVectores.setFixedSize(551, 424)
        self.centralwidget = QtWidgets.QWidget(parent=SumaVectores)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 551, 391))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Imagenes/fondo.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_14 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(70, 0, 401, 81))
        self.label_14.setText("")
        self.label_14.setPixmap(QtGui.QPixmap("Imagenes/Captura_de_pantalla_2024-05-22_230220-removebg-preview.png"))
        self.label_14.setScaledContents(True)
        self.label_14.setObjectName("label_14")
        self.plainTextEdit_3 = QtWidgets.QPlainTextEdit(parent=self.centralwidget)
        self.plainTextEdit_3.setGeometry(QtCore.QRect(160, 140, 81, 31))
        self.plainTextEdit_3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.plainTextEdit_3.setObjectName("plainTextEdit_3")
        self.label_15 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(40, 90, 181, 31))
        self.label_15.setText("")
        self.label_15.setPixmap(QtGui.QPixmap("Imagenes/Captura_de_pantalla_2024-05-22_232244-removebg-preview.png"))
        self.label_15.setScaledContents(True)
        self.label_15.setObjectName("label_15")
        self.textBrowser = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(370, 200, 151, 31))
        self.textBrowser.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.textBrowser.setObjectName("textBrowser")
        self.label_13 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(370, 140, 141, 51))
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap("Imagenes/Captura_de_pantalla_2024-05-21_190303-removebg-preview.png"))
        self.label_13.setScaledContents(True)
        self.label_13.setObjectName("label_13")
        self.pushButton_23 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_23.setGeometry(QtCore.QRect(260, 200, 81, 41))
        self.pushButton_23.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_23.setStyleSheet("background-color: rgb(0, 129, 185);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_23.setObjectName("pushButton_23")
        self.pushButton_27 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_27.setGeometry(QtCore.QRect(480, 300, 61, 61))
        self.pushButton_27.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_27.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(218, 218, 218);\n"
"\n"
"\n"
"border-radius: 30px;\n"
"")
        self.pushButton_27.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Imagenes/files.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_27.setIcon(icon)
        self.pushButton_27.setObjectName("pushButton_27")
        self.plainTextEdit_4 = QtWidgets.QPlainTextEdit(parent=self.centralwidget)
        self.plainTextEdit_4.setGeometry(QtCore.QRect(160, 200, 81, 31))
        self.plainTextEdit_4.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.plainTextEdit_4.setObjectName("plainTextEdit_4")
        self.plainTextEdit_5 = QtWidgets.QPlainTextEdit(parent=self.centralwidget)
        self.plainTextEdit_5.setGeometry(QtCore.QRect(160, 320, 81, 31))
        self.plainTextEdit_5.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.plainTextEdit_5.setObjectName("plainTextEdit_5")
        self.plainTextEdit_6 = QtWidgets.QPlainTextEdit(parent=self.centralwidget)
        self.plainTextEdit_6.setGeometry(QtCore.QRect(160, 260, 81, 31))
        self.plainTextEdit_6.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.plainTextEdit_6.setObjectName("plainTextEdit_6")
        self.label_16 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(50, 140, 91, 31))
        self.label_16.setText("")
        self.label_16.setPixmap(QtGui.QPixmap("Imagenes/Captura_de_pantalla_2024-05-22_232619-removebg-preview.png"))
        self.label_16.setScaledContents(True)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(50, 200, 81, 31))
        self.label_17.setText("")
        self.label_17.setPixmap(QtGui.QPixmap("Imagenes/Captura_de_pantalla_2024-05-22_232846-removebg-preview.png"))
        self.label_17.setScaledContents(True)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(50, 260, 81, 31))
        self.label_18.setText("")
        self.label_18.setPixmap(QtGui.QPixmap("Imagenes/Captura_de_pantalla_2024-05-22_233024-removebg-preview.png"))
        self.label_18.setScaledContents(True)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(50, 320, 81, 41))
        self.label_19.setText("")
        self.label_19.setPixmap(QtGui.QPixmap("Imagenes/Captura_de_pantalla_2024-05-22_233409-removebg-preview.png"))
        self.label_19.setScaledContents(True)
        self.label_19.setObjectName("label_19")
        SumaVectores.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=SumaVectores)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 551, 26))
        self.menubar.setObjectName("menubar")
        SumaVectores.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=SumaVectores)
        self.statusbar.setObjectName("statusbar")
        SumaVectores.setStatusBar(self.statusbar)

        self.retranslateUi(SumaVectores)
        QtCore.QMetaObject.connectSlotsByName(SumaVectores)

    def retranslateUi(self, SumaVectores):
        _translate = QtCore.QCoreApplication.translate
        SumaVectores.setWindowTitle(_translate("SumaVectores", "Suma de Vectores"))
        self.pushButton_23.setText(_translate("SumaVectores", "Sumar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SumaVectores = QtWidgets.QMainWindow()
    ui = Ui_SumaVectores()
    ui.setupUi(SumaVectores)
    SumaVectores.show()
    sys.exit(app.exec())
